// languages.js
export const allLanguages = [
  { language: "python", version: "3.10.0" },
  { language: "javascript", version: "18.15.0" },
  { language: "typescript", version: "5.0.3" },
  { language: "java", version: "15.0.2" },
  { language: "c", version: "10.2.0" },
  { language: "c++", version: "10.2.0" },
  { language: "csharp.net", version: "5.0.201" },
  { language: "csharp", version: "6.12.0" },
  { language: "go", version: "1.16.2" },
  { language: "rust", version: "1.68.2" },
  { language: "ruby", version: "3.0.1" },
  { language: "php", version: "8.2.3" },
  { language: "swift", version: "5.3.3" },
  { language: "kotlin", version: "1.8.20" },
  { language: "scala", version: "3.2.2" },
  { language: "perl", version: "5.36.0" },
  { language: "rscript", version: "4.1.1" },
  { language: "bash", version: "5.2.0" },
  { language: "powershell", version: "7.1.4" },
  { language: "racket", version: "8.3.0" },
  { language: "julia", version: "1.8.5" },
  { language: "elixir", version: "1.11.3" },
  { language: "dart", version: "2.19.6" },
  { language: "haskell", version: "9.0.1" },
  { language: "lua", version: "5.4.4" },
  { language: "fsharp.net", version: "5.0.201" },
  { language: "basic.net", version: "5.0.201" },
  { language: "ocaml", version: "4.12.0" },
  { language: "pascal", version: "3.2.2" },
];
